export default {
    courses: [],
    flashroster: [],
    studentImages: {},
    menuShow: false,
    list: true,
    flash: false,
    sortLastName: true,
    sortDescending: true,
    errors: null,
    themeName: {theme: 'theme-OnceAMatadorAlwaysAMatador'},
    hideBack: true,
    disableBack: false,
    semester: null,
    termYear: null,
    term: null,
    displayTerm: null,
    loadingClasses: true,
    imagePermission: null,

    facultyMember: {
        email: null,
        emailURI: null,
        profile: null,
        firstName: null,
        lastName: null,
        image: null,
        id: null
    },
}
